Add admin-page link to people-page: Addresses issue#53
agile-learning-institute/mentorHub-person-ui pull request #60
Opened 2024-03-12 21:42 UTC by WodPachua

Added Admin Page Link to the People Page, a Fix for [Issue#53](https://github.com/agile-learning-institute/mentorHub-person-ui/issues/53)

2024-03-12 21:53 UTC, FlatBallFlyer requested changes
Seems like we should use the vuetify classes for ``d-flex flex-row flex-wrap justify-center`` instead of extending the mb-5 style. I'm also not a fan of the blue button - I mean I guess it's ok, but it does add color to a decidedly white-label style. We do have folks looking to provide a more opinionated style, colors, etc. so I might hold off on creating variety for the time being.

2024-03-12 22:26 UTC, WodPachua commented
@FlatBallFlyer Here is a screen shot of new changes based on previous comments/suggestions

![image](https://github.com/agile-learning-institute/mentorHub-person-ui/assets/19221635/78e07f09-f454-4009-bff4-702106b3c8bb)

2024-03-12 23:17 UTC, FlatBallFlyer approved these changes

2024-03-13 00:44 UTC, FlatBallFlyer approved these changes

2024-03-13 00:44 UTC, merged